listen:
  port: 4040

namespaces: 
  - name: nginx 
    format: "{\"time_local\":\"$time_local\",\"remote_addr\":\"$remote_addr\",\"remote_user\":\"$remote_user\",\"request\":\"$request\",\"status\":\"$status\",\"body_bytes_sent\":\"$body_bytes_sent\",\"request_time\":\"$request_time\",\"http_referrer\":\"$http_referer\",\"http_user_agent\":\"$http_user_agent\"}"
    source:
      files:
        - "mnt/nginxlogs/access.log"
        
    labels:
      label1: "label1"
      label2: "label2"
      label3: "label3"

    histogram_buckets: [.005, .01, .025, .05, .1, .25, .5, 1, 2.5, 5, 10]
