version: '2.2'

networks:
  monitoring:
    driver: bridge 
    
volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'     
    ports:
      - "9090:9090"
    expose:
      - 9090   
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    environment:
      # - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      # - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false        
    ports:
      - "3000:3000"
    expose:
      - 3000
    networks:
      - monitoring

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/nginx/logs:/var/log/nginx  
    command: ['nginx', '-g', 'daemon off;']
    ports:
      - "80:80"
    expose:
      - 80
    networks:
      - monitoring

  nginxlog-exporter:
    image: quay.io/martinhelmich/prometheus-nginxlog-exporter
    container_name: nginxlog-exporter
    restart: unless-stopped
    volumes:
      - ${PWD}/nginx/logs:/mnt/nginxlogs
      - ${PWD}/config.yaml:/etc/prometheus-nginxlog-exporter.yaml
    command: 
      - -config-file 
      - /etc/prometheus-nginxlog-exporter.yaml 
    ports:
      - "4040:4040"
    expose:
      - 4040
    networks:
      - monitoring
    depends_on:
      - nginx   
 


